abi = "DELETE THIS STRING AND REPLACE WITH ABI LIST"


smartContractAddress = "SMART CONTRACT ADDRESS GOES HERE"

casinoPrivateKey = "PRIVATE KEY OF WALLET OF CASINO GOES HERE"

web3Provider = "WEB3 PROVIDER GOES HERE"